import { db } from './index.ts';
import { 
  tenants, users, employees, clients, contracts, scaleAllocations, 
  providers, assets, assetAllocations, maintenances, 
  auditLogs, employeeOccurrences, appNotifications 
} from './schema.ts';

const SEED_EMPLOYEES = [
  {
    id: 'emp-1',
    name: 'Carlos Eduardo Souza',
    cpf: '123.456.789-00',
    rg: '12.345.678-9',
    birthDate: '1985-05-12',
    gender: 'Masculino',
    civilStatus: 'Casado',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    address: 'Av. Paulista, 1000 - Apt 42',
    city: 'São Paulo',
    state: 'SP',
    cep: '01310-100',
    phone: '(11) 98888-7777',
    whatsapp: '(11) 98888-7777',
    email: 'carlos.supervisor@evolution.com',
    admissionDate: '2020-03-10',
    role: 'Supervisor',
    function: 'Supervisor de Operações',
    supervisorId: null,
    scaleType: '5x2',
    shift: 'Diurno',
    situation: 'Ativo',
    salary: 4800,
    bankName: 'Itaú Unibanco',
    bankAgency: '3829',
    bankAccount: '19283-4',
    pixKey: 'carlos.supervisor@evolution.com',
    cnhUrl: 'cnh_carlos.pdf',
    vigilanteCourseUrl: 'curso_carlos.pdf',
    recyclingUrl: 'reciclagem_carlos.pdf',
    asoUrl: 'aso_carlos.pdf',
    certificatesUrls: [],
    createdAt: '2020-03-10T10:00:00Z',
  },
  {
    id: 'emp-2',
    name: 'Roberto Silva Oliveira',
    cpf: '987.654.321-11',
    rg: '98.765.432-1',
    birthDate: '1990-08-22',
    gender: 'Masculino',
    civilStatus: 'Solteiro',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    address: 'Rua das Flores, 123',
    city: 'São Paulo',
    state: 'SP',
    cep: '04567-000',
    phone: '(11) 97777-6666',
    whatsapp: '(11) 97777-6666',
    email: 'roberto.vigilante@evolution.com',
    admissionDate: '2021-06-15',
    role: 'Vigilante',
    function: 'Vigilante de Escolta',
    supervisorId: 'emp-1',
    scaleType: '12x36',
    shift: 'Noturno',
    situation: 'Ativo',
    salary: 3200,
    bankName: 'Banco do Brasil',
    bankAgency: '0123',
    bankAccount: '98765-2',
    pixKey: '987.654.321-11',
    cnhUrl: 'cnh_roberto.pdf',
    vigilanteCourseUrl: 'curso_roberto.pdf',
    recyclingUrl: 'reciclagem_roberto.pdf',
    asoUrl: 'aso_roberto.pdf',
    certificatesUrls: [],
    createdAt: '2021-06-15T11:00:00Z',
  },
  {
    id: 'emp-3',
    name: 'Mariana Costa Ramos',
    cpf: '456.789.123-22',
    rg: '45.678.912-3',
    birthDate: '1993-11-04',
    gender: 'Feminino',
    civilStatus: 'Divorciado',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    address: 'Av. Brigadeiro Luís Antônio, 2500',
    city: 'São Paulo',
    state: 'SP',
    cep: '01402-000',
    phone: '(11) 96666-5555',
    whatsapp: '(11) 96666-5555',
    email: 'mariana.rh@evolution.com',
    admissionDate: '2022-01-10',
    role: 'RH',
    function: 'Analista de Recursos Humanos',
    supervisorId: null,
    scaleType: '5x2',
    shift: 'Diurno',
    situation: 'Ativo',
    salary: 4100,
    bankName: 'Santander',
    bankAgency: '2244',
    bankAccount: '11223-9',
    pixKey: 'mariana.rh@evolution.com',
    certificatesUrls: [],
    createdAt: '2022-01-10T09:00:00Z',
  },
  {
    id: 'emp-4',
    name: 'Alexandre Pires',
    cpf: '234.567.890-11',
    rg: '23.456.789-0',
    birthDate: '1988-02-14',
    gender: 'Masculino',
    civilStatus: 'Casado',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    address: 'Rua Augusta, 1800',
    city: 'São Paulo',
    state: 'SP',
    cep: '01305-100',
    phone: '(11) 95555-4444',
    whatsapp: '(11) 95555-4444',
    email: 'alexandre.vigilante@evolution.com',
    admissionDate: '2023-02-20',
    role: 'Vigilante',
    function: 'Vigilante Patrimonial',
    supervisorId: 'emp-1',
    scaleType: '12x36',
    shift: 'Matutino',
    situation: 'Ativo',
    salary: 3100,
    bankName: 'Caixa Econômica Federal',
    bankAgency: '1040',
    bankAccount: '88771-5',
    pixKey: 'alexandre.vigilante@evolution.com',
    cnhUrl: 'cnh_alexandre.pdf',
    vigilanteCourseUrl: 'curso_alexandre.pdf',
    recyclingUrl: 'reciclagem_alexandre.pdf',
    asoUrl: 'aso_alexandre.pdf',
    certificatesUrls: [],
    createdAt: '2023-02-20T08:30:00Z',
  },
  {
    id: 'emp-5',
    name: 'Juliana Mendes Melo',
    cpf: '345.678.901-22',
    rg: '34.567.890-1',
    birthDate: '1992-04-30',
    gender: 'Feminino',
    civilStatus: 'Solteiro',
    photoUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop&q=80',
    address: 'Av. Rebouças, 1200',
    city: 'São Paulo',
    state: 'SP',
    cep: '05402-000',
    phone: '(11) 94444-3333',
    whatsapp: '(11) 94444-3333',
    email: 'juliana.mendes@evolution.com',
    admissionDate: '2024-01-15',
    role: 'Vigilante',
    function: 'Vigilante de Posto',
    supervisorId: 'emp-1',
    scaleType: '12x36',
    shift: 'Vespertino',
    situation: 'Afastado',
    salary: 3100,
    bankName: 'Itaú Unibanco',
    bankAgency: '3829',
    bankAccount: '33221-5',
    pixKey: '345.678.901-22',
    asoUrl: 'aso_juliana.pdf',
    certificatesUrls: [],
    createdAt: '2024-01-15T09:00:00Z',
  }
];

const SEED_CLIENTS = [
  {
    id: 'cli-1',
    type: 'PJ',
    name: 'Condomínio Residencial Parque das Flores',
    tradeName: 'Parque das Flores',
    document: '12.345.678/0001-99',
    contactPhone: '(11) 3211-4400',
    contactEmail: 'gerencia@parquedasflores.com.br',
    responsibleName: 'Sr. Marcos Aurelio Fontes (Síndico)',
    responsiblePhone: '(11) 99111-2222',
    address: 'Alameda das Acácias, 500',
    city: 'São Paulo',
    state: 'SP',
    cep: '04500-010',
    notes: 'Necessita de rondas motorizadas periódicas no perímetro.',
    status: 'Ativo',
    createdAt: '2022-01-15T08:00:00Z',
  },
  {
    id: 'cli-2',
    type: 'PJ',
    name: 'Indústrias Metalúrgicas Alfa S.A.',
    tradeName: 'Indústria Alfa',
    document: '98.765.432/0001-88',
    contactPhone: '(11) 3500-9900',
    contactEmail: 'seguranca@metalurgicaalfa.com.br',
    responsibleName: 'Eng. Roberto Vasconcelos',
    responsiblePhone: '(11) 98222-3333',
    address: 'Av. Industrial, 4500',
    city: 'Guarulhos',
    state: 'SP',
    cep: '07110-000',
    notes: 'Exige vigilante armado 24h e controle de acesso rigoroso de carretas.',
    status: 'Ativo',
    createdAt: '2023-04-10T09:00:00Z',
  },
  {
    id: 'cli-3',
    type: 'PF',
    name: 'Fernando Henrique Lima',
    tradeName: '',
    document: '234.567.890-44',
    contactPhone: '(11) 97111-4444',
    contactEmail: 'fhl@advocacialima.com.br',
    responsibleName: 'Fernando Henrique Lima',
    responsiblePhone: '',
    address: 'Rua Suécia, 120',
    city: 'São Paulo',
    state: 'SP',
    cep: '01440-000',
    notes: 'Escolta pessoal VIP em eventos específicos e fins de semana.',
    status: 'Ativo',
    createdAt: '2024-02-18T14:00:00Z',
  }
];

const getContracts = () => {
  const today = new Date();
  const dateIn5Days = new Date();
  dateIn5Days.setDate(today.getDate() + 5);
  const dateIn14Days = new Date();
  dateIn14Days.setDate(today.getDate() + 14);
  const dateIn180Days = new Date();
  dateIn180Days.setDate(today.getDate() + 180);

  return [
    {
      id: 'con-1',
      clientId: 'cli-1',
      clientName: 'Condomínio Residencial Parque das Flores',
      contractNumber: 'CT-2026-001',
      startDate: '2024-01-01',
      endDate: dateIn14Days.toISOString().split('T')[0],
      monthlyValue: 18500,
      postCount: 2,
      securityGuardCount: 4,
      contractType: 'Vigilância Patrimonial Desarmada 12x36',
      situation: 'Ativo',
      notes: 'Posto Portaria A e Ronda Interna B.',
      pdfUrl: '',
      createdAt: '2024-01-01T10:00:00Z',
    },
    {
      id: 'con-2',
      clientId: 'cli-2',
      clientName: 'Indústrias Metalúrgicas Alfa S.A.',
      contractNumber: 'CT-2026-002',
      startDate: '2023-05-01',
      endDate: dateIn5Days.toISOString().split('T')[0],
      monthlyValue: 32000,
      postCount: 3,
      securityGuardCount: 6,
      contractType: 'Vigilância Armada 24h e Controle de Acesso',
      situation: 'Ativo',
      notes: 'Portaria principal armada, ronda externa em moto, controle de docas.',
      pdfUrl: '',
      createdAt: '2023-05-01T10:00:00Z',
    },
    {
      id: 'con-3',
      clientId: 'cli-3',
      clientName: 'Fernando Henrique Lima',
      contractNumber: 'CT-2026-003',
      startDate: '2024-02-20',
      endDate: dateIn180Days.toISOString().split('T')[0],
      monthlyValue: 12000,
      postCount: 1,
      securityGuardCount: 2,
      contractType: 'Escolta Pessoal / Segurança VIP',
      situation: 'Ativo',
      notes: 'Segurança privada móvel.',
      pdfUrl: '',
      createdAt: '2024-02-20T10:00:00Z',
    }
  ];
};

const getScales = () => {
  const todayStr = new Date().toISOString().split('T')[0];
  const tomorrowStr = new Date(Date.now() + 86400000).toISOString().split('T')[0];
  
  return [
    {
      id: 'sca-1',
      employeeId: 'emp-2',
      employeeName: 'Roberto Silva Oliveira',
      clientId: 'cli-2',
      clientName: 'Indústrias Metalúrgicas Alfa S.A.',
      contractId: 'con-2',
      contractNumber: 'CT-2026-002',
      postName: 'Portaria Docas',
      shift: 'Noturno',
      scaleType: '12x36',
      isOffDay: false,
      startDate: `${todayStr}T18:00:00`,
      endDate: `${tomorrowStr}T06:00:00`,
      overtimeHours: 0,
      notes: 'Posto fixo Docas Norte.',
      createdAt: '2026-07-16T12:00:00Z',
    },
    {
      id: 'sca-2',
      employeeId: 'emp-4',
      employeeName: 'Alexandre Pires',
      clientId: 'cli-1',
      clientName: 'Condomínio Residencial Parque das Flores',
      contractId: 'con-1',
      contractNumber: 'CT-2026-001',
      postName: 'Guarita Principal',
      shift: 'Matutino',
      scaleType: '12x36',
      isOffDay: false,
      startDate: `${todayStr}T06:00:00`,
      endDate: `${todayStr}T18:00:00`,
      overtimeHours: 2,
      notes: 'Substituição pontual por 2 horas extras devido a trânsito.',
      createdAt: '2026-07-16T12:00:00Z',
    }
  ];
};

const SEED_PROVIDERS = [
  {
    id: 'prov-1',
    cnpj: '00.123.456/0001-00',
    companyName: 'Taurus Armas S.A.',
    tradeName: 'Forjas Taurus',
    contactName: 'Carlos Silveira',
    phone: '(51) 3020-5000',
    email: 'vendas@taurus.com.br',
    suppliedProducts: 'Armas de Fogo, Coldres, Algemas e Munições',
    notes: 'Homologado oficial pela Polícia Federal para fornecimento de material controlado.',
    createdAt: '2020-01-01T10:00:00Z',
    contactPhone: '',
    contactEmail: '',
    address: '',
    serviceProvided: '',
  },
  {
    id: 'prov-2',
    cnpj: '11.222.333/0001-44',
    companyName: 'Motorola Solutions Ltda',
    tradeName: 'Motorola Soluções',
    contactName: 'Julio Cesar Melo',
    phone: '(11) 4004-3290',
    email: 'julio@motorolasolutions.com',
    suppliedProducts: 'Rádios Comunicadores, Repetidoras e Fones de Ouvido',
    notes: 'Fornecedor de telecomunicações táticas.',
    createdAt: '2021-02-15T09:00:00Z',
    contactPhone: '',
    contactEmail: '',
    address: '',
    serviceProvided: '',
  },
  {
    id: 'prov-3',
    cnpj: '22.333.444/0001-55',
    companyName: 'Evolution Auto e Mecânica Ltda',
    tradeName: 'Oficina Mecânica Evolution',
    contactName: 'André Marins',
    phone: '(11) 98111-5544',
    email: 'andre@oficinaevolution.com.br',
    suppliedProducts: 'Manutenção de frotas de carros e motos',
    notes: 'Parceiro local para vistorias periódicas de carros de ronda.',
    createdAt: '2022-03-10T11:00:00Z',
    contactPhone: '',
    contactEmail: '',
    address: '',
    serviceProvided: '',
  }
];

const SEED_ASSETS = [
  {
    id: 'ast-1',
    assetNumber: 'PAT-0012',
    serialNumber: 'TA-382910',
    category: 'Arma',
    brand: 'Taurus',
    model: 'Revólver .38 4" Oxidado',
    providerId: 'prov-1',
    providerName: 'Taurus Armas S.A.',
    purchaseDate: '2022-05-10',
    purchaseValue: 3800,
    warrantyEndDate: '2027-05-10',
    situation: 'Emprestado',
    photoUrl: '',
    notes: 'Arma sob cautela específica registrada com termo assinado.',
    qrCodeUrl: '',
    barcodeValue: '789012382910',
    createdAt: '2022-05-10T12:00:00Z',
  },
  {
    id: 'ast-2',
    assetNumber: 'PAT-0044',
    serialNumber: 'MOT-92019',
    category: 'Rádio Comunicador',
    brand: 'Motorola',
    model: 'Rádio Portátil DEP450',
    providerId: 'prov-2',
    providerName: 'Motorola Solutions Ltda',
    purchaseDate: '2023-01-20',
    purchaseValue: 1400,
    warrantyEndDate: '2025-01-20',
    situation: 'Disponível',
    photoUrl: '',
    notes: 'Frequência criptografada homologada pela ANATEL.',
    qrCodeUrl: '',
    barcodeValue: '789012392019',
    createdAt: '2023-01-20T12:00:00Z',
  },
  {
    id: 'ast-3',
    assetNumber: 'PAT-0125',
    serialNumber: 'PLA-EVO2A26',
    category: 'Carros',
    brand: 'Chevrolet',
    model: 'Onix Hatch 1.0 Turbo',
    providerId: 'prov-3',
    providerName: 'Evolution Auto e Mecânica Ltda',
    purchaseDate: '2024-03-10',
    purchaseValue: 82000,
    warrantyEndDate: '2027-03-10',
    situation: 'Emprestado',
    photoUrl: '',
    notes: 'Identificado com plotagem completa Evolution e giroflex homologado.',
    qrCodeUrl: '',
    barcodeValue: '789012401250',
    createdAt: '2024-03-10T10:00:00Z',
  },
  {
    id: 'ast-4',
    assetNumber: 'PAT-0082',
    serialNumber: 'COL-7729',
    category: 'Colete',
    brand: 'CBC Proteções',
    model: 'Colete Balístico Nível IIIA',
    providerId: 'prov-1',
    providerName: 'Taurus Armas S.A.',
    purchaseDate: '2023-07-15',
    purchaseValue: 1800,
    warrantyEndDate: '2028-07-15',
    situation: 'Manutenção',
    photoUrl: '',
    notes: 'Em manutenção para troca de capa desgastada e vistoria da placa balística.',
    qrCodeUrl: '',
    barcodeValue: '789012400820',
    createdAt: '2023-07-15T09:00:00Z',
  }
];

const SEED_ALLOCATIONS = [
  {
    id: 'alc-1',
    assetId: 'ast-1',
    assetNumber: 'PAT-0012',
    assetName: 'Taurus Revólver .38 4" Oxidado',
    targetType: 'Funcionário',
    targetId: 'emp-2',
    targetName: 'Roberto Silva Oliveira',
    allocationDate: '2026-07-01',
    returnDate: null,
    expectedReturnDate: '2026-12-31',
    registeredBy: 'Carlos Eduardo Souza',
    equipmentCondition: 'Excelente',
    digitalSignature: 'Roberto Silva Oliveira',
    historyNotes: 'Cautela de arma carregada com 12 cartuchos ponta oca.',
    createdAt: '2026-07-01T12:00:00Z',
  },
  {
    id: 'alc-2',
    assetId: 'ast-3',
    assetNumber: 'PAT-0125',
    assetName: 'Chevrolet Onix Hatch 1.0 Turbo',
    targetType: 'Funcionário',
    targetId: 'emp-1',
    targetName: 'Carlos Eduardo Souza',
    allocationDate: '2026-07-10',
    returnDate: null,
    expectedReturnDate: '2026-07-20',
    registeredBy: 'Mariana Costa Ramos',
    equipmentCondition: 'Regular',
    digitalSignature: 'Carlos E Souza',
    historyNotes: 'Veículo com pequenos riscos no para-choque traseiro.',
    createdAt: '2026-07-10T14:00:00Z',
  }
];

const SEED_MAINTENANCE = [
  {
    id: 'mnt-1',
    assetId: 'ast-4',
    assetNumber: 'PAT-0082',
    assetName: 'CBC Proteções Colete Balístico Nível IIIA',
    entryDate: '2026-07-14',
    issueDescription: 'Zíper frontal quebrado e necessidade de costura de suporte de rádio.',
    providerId: 'prov-1',
    providerName: 'Taurus Armas S.A.',
    cost: 150,
    exitDate: null,
    warrantyEndDate: null,
    attachmentUrl: '',
    createdAt: '2026-07-14T10:00:00Z',
  }
];

const SEED_AUDIT_LOGS = [
  {
    id: 'aud-1',
    userId: 'usr-1',
    userName: 'Administrador Evolution',
    userRole: 'Administrador',
    action: 'Login',
    module: 'Auth',
    details: 'Autenticação realizada com sucesso via e-mail e senha.',
    ipAddress: '200.141.22.45',
    beforeState: '',
    afterState: '',
    createdAt: '2026-07-16T10:00:00Z',
  },
  {
    id: 'aud-2',
    userId: 'usr-1',
    userName: 'Administrador Evolution',
    userRole: 'Administrador',
    action: 'Cadastrar',
    module: 'Employees',
    details: 'Cadastro do funcionário Roberto Silva Oliveira (Vigilante) realizado com sucesso.',
    ipAddress: '200.141.22.45',
    beforeState: '',
    afterState: '',
    createdAt: '2026-07-16T10:15:00Z',
  }
];

const SEED_OCCURRENCES = [
  {
    id: 'occ-1',
    employeeId: 'emp-1',
    type: 'Admissão',
    date: '2020-03-10',
    endDate: null,
    notes: 'Admissão original do supervisor de operações.',
    attachmentUrl: '',
    registeredBy: 'Sistema',
    createdAt: '2020-03-10T10:00:00Z',
    version: 1,
    admissionDate: '2020-03-10',
    role: 'Supervisor',
    department: 'Operações',
    unit: 'Sede Principal',
    supervisorId: null,
  },
  {
    id: 'occ-2',
    employeeId: 'emp-2',
    type: 'Admissão',
    date: '2021-06-15',
    endDate: null,
    notes: 'Admissão original do vigilante de escolta.',
    attachmentUrl: '',
    registeredBy: 'Sistema',
    createdAt: '2021-06-15T11:00:00Z',
    version: 1,
    admissionDate: '2021-06-15',
    role: 'Vigilante',
    department: 'Escolta',
    unit: 'Sede Principal',
    supervisorId: 'emp-1',
  },
  {
    id: 'occ-3',
    employeeId: 'emp-3',
    type: 'Admissão',
    date: '2022-01-10',
    endDate: null,
    notes: 'Admissão original da analista de RH.',
    attachmentUrl: '',
    registeredBy: 'Sistema',
    createdAt: '2022-01-10T09:00:00Z',
    version: 1,
    admissionDate: '2022-01-10',
    role: 'RH',
    department: 'Recursos Humanos',
    unit: 'Sede Principal',
    supervisorId: null,
  },
  {
    id: 'occ-4',
    employeeId: 'emp-4',
    type: 'Admissão',
    date: '2023-02-20',
    endDate: null,
    notes: 'Admissão original do vigilante patrimonial.',
    attachmentUrl: '',
    registeredBy: 'Sistema',
    createdAt: '2023-02-20T08:30:00Z',
    version: 1,
    admissionDate: '2023-02-20',
    role: 'Vigilante',
    department: 'Operações',
    unit: 'Sede Principal',
    supervisorId: 'emp-1',
  },
  {
    id: 'occ-5',
    employeeId: 'emp-5',
    type: 'Admissão',
    date: '2024-01-15',
    endDate: null,
    notes: 'Admissão original da vigilante de posto.',
    attachmentUrl: '',
    registeredBy: 'Sistema',
    createdAt: '2024-01-15T09:00:00Z',
    version: 1,
    admissionDate: '2024-01-15',
    role: 'Vigilante',
    department: 'Operações',
    unit: 'Sede Principal',
    supervisorId: 'emp-1',
  },
  {
    id: 'occ-6',
    employeeId: 'emp-5',
    type: 'Afastamento',
    date: '2026-07-10',
    endDate: '2026-07-30',
    notes: 'Afastamento médico para tratamento de dor lombar crônica.',
    attachmentUrl: '',
    registeredBy: 'Mariana Costa Ramos',
    createdAt: '2026-07-10T10:00:00Z',
    version: 1,
    absenceType: 'Auxílio Doença',
    cid: 'M54.5',
  }
];

export async function seedDatabase() {
  try {
    const existingEmployees = await db.select().from(employees).limit(1);
    if (existingEmployees.length > 0) {
      console.log('Database already seeded.');
      return;
    }

    console.log('Seeding database with default multi-tenant records...');

    await db.insert(tenants).values([
      {
        id: 'tenant-demo-1',
        name: 'EVOLUTIONSEG Grupo Demonstração',
        cnpj: '12.345.678/0001-90',
        plan: 'Pro',
        status: 'Ativo',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'tenant-demo-2',
        name: 'Empresa de Segurança Beta LTDA',
        cnpj: '98.765.432/0001-10',
        plan: 'Enterprise',
        status: 'Ativo',
        createdAt: new Date().toISOString(),
      }
    ]).onConflictDoNothing();

    await db.insert(employees).values(SEED_EMPLOYEES.map(e => ({ ...e, tenantId: 'tenant-demo-1' })));
    await db.insert(clients).values(SEED_CLIENTS.map(c => ({ ...c, tenantId: 'tenant-demo-1' })));
    await db.insert(contracts).values(getContracts().map(c => ({ ...c, tenantId: 'tenant-demo-1' })));
    await db.insert(scaleAllocations).values(getScales().map(s => ({ ...s, tenantId: 'tenant-demo-1' })));
    await db.insert(providers).values(SEED_PROVIDERS.map(p => ({ ...p, tenantId: 'tenant-demo-1' })));
    await db.insert(assets).values(SEED_ASSETS.map(a => ({ ...a, tenantId: 'tenant-demo-1' })));
    await db.insert(assetAllocations).values(SEED_ALLOCATIONS.map(a => ({ ...a, tenantId: 'tenant-demo-1' })));
    await db.insert(maintenances).values(SEED_MAINTENANCE.map(m => ({ ...m, tenantId: 'tenant-demo-1' })));
    await db.insert(auditLogs).values(SEED_AUDIT_LOGS.map(a => ({ ...a, tenantId: 'tenant-demo-1' })));
    await db.insert(employeeOccurrences).values(SEED_OCCURRENCES.map(o => ({ ...o, tenantId: 'tenant-demo-1' })));

    console.log('Multi-tenant Seeding completed successfully!');
  } catch (error) {
    console.error('Error seeding database:', error);
  }
}
